# This is a basic workflow to help you get started with Actions

name: CI/CD
on:
  #manual
  #workflow_dispatch:

  #On push
   push:
     branches: [ "main" ]
  
  #On pull_request
  # pull_request:
  #   branches: [ "main" ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  terraform-integration:
    runs-on: [self-hosted, k0s, ephemeral]
    defaults:
      run:
        working-directory: ./k0s
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5
      - name: Terraform Init, Validate & Plan
        env:
          PROXMOX_API_URL: ${{ secrets.PROXMOX_API_URL }}
          PROXMOX_USERNAME: ${{ secrets.PROXMOX_USERNAME }}
          PROXMOX_TOKEN_ID: ${{ secrets.PROXMOX_TOKEN_ID }}
          PROXMOX_TOKEN: ${{ secrets.PROXMOX_TOKEN }}
          G_TOKEN: ${{ secrets.G_TOKEN }}
          APP_ID: ${{ secrets.APP_ID }}
          APP_INSTALLATION_ID: ${{ secrets.APP_INSTALLATION_ID }}
        run: |
          cat > terraform.tfvars <<EOF
          echo "proxmox_api_url     = "${PROXMOX_API_URL}"" > terraform.tfvars
          echo "proxmox_username    = "${PROXMOX_USERNAME}"" >> terraform.tfvars
          echo "proxmox_token_id    = "${PROXMOX_TOKEN_ID}"" >> terraform.tfvars
          echo "proxmox_token       = "${PROXMOX_TOKEN}"" >> terraform.tfvars
          echo "node                = "node1"" >> terraform.tfvars
          echo "nodes               = ["node1", "pxmaster"]" >> terraform.tfvars
          echo "storage_pool        = "local-lvm"" >> terraform.tfvars
          echo "vm_user             = "root"" >> terraform.tfvars
          echo "vm_private_key_path = "/root/.ssh/id_rsa"" >> terraform.tfvars
          echo "templete            = "k0s"" >> terraform.tfvars
          echo "ram                 = 4096" >> terraform.tfvars
          echo "core                = 2" >> terraform.tfvars
          echo "ips_master          = ["192.168.99.165", "192.168.99.166", "192.168.99.167"]" >> terraform.tfvars
          echo "ips_nodes           = ["192.168.99.176", "192.168.99.177", "192.168.99.178"]" >> terraform.tfvars
          echo "gw                  = "192.168.99.1"" >> terraform.tfvars
          echo "gitrepo             = "action-runner-local"" >> terraform.tfvars
          echo "github_app_id       = "${APP_ID}"" >> terraform.tfvars
          echo "github_app_installation_id = "${APP_INSTALLATION_ID}"" >> terraform.tfvars
          echo "git_token           = "${G_TOKEN}"" >> terraform.tfvars

          terraform init -upgrade
          terraform validate
          terraform plan