# This is a basic workflow to help you get started with Actions

name: CI/CD
on:
  #manual
  #workflow_dispatch:
   push:
     branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  terraform-integration:
    runs-on: [self-hosted, k0s, ephemeral]
    defaults:
      run:
        working-directory: ./k0s
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5
      - name: Terraform Init, Validate & Plan
        run: |
          terraform init -upgrade
          terraform validate
          terraform plan